// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzxz9omjAPGNpX0WtdSeadgxVZ8eFpq1U',
    appId: '1:418260845222:web:8b00c1931e17f772d3ea67',
    messagingSenderId: '418260845222',
    projectId: 'initnews-4a2d7',
    authDomain: 'initnews-4a2d7.firebaseapp.com',
    storageBucket: 'initnews-4a2d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6lR0RgZagaZLybxXfMavKi-bBj8tdUyA',
    appId: '1:418260845222:android:a557492e93027ef9d3ea67',
    messagingSenderId: '418260845222',
    projectId: 'initnews-4a2d7',
    storageBucket: 'initnews-4a2d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6hRansusHQnaCM9D4tePMRA960EvT2b8',
    appId: '1:418260845222:ios:95a32f532a71de19d3ea67',
    messagingSenderId: '418260845222',
    projectId: 'initnews-4a2d7',
    storageBucket: 'initnews-4a2d7.appspot.com',
    iosClientId: '418260845222-o2li6efqa4esv1bbter45irf95fqd0dc.apps.googleusercontent.com',
    iosBundleId: 'io.initappz.flutter.init.news',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6hRansusHQnaCM9D4tePMRA960EvT2b8',
    appId: '1:418260845222:ios:e572666438f80771d3ea67',
    messagingSenderId: '418260845222',
    projectId: 'initnews-4a2d7',
    storageBucket: 'initnews-4a2d7.appspot.com',
    iosClientId: '418260845222-7erbs3a2tc49o6a4hfrruvriv8avsiof.apps.googleusercontent.com',
    iosBundleId: 'com.example.ultimateNews.RunnerTests',
  );
}
