import "package:get/get.dart";

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "Profile": "Profile",
          "Sign In / Sign Up": "Sign In / Sign Up",
          "Settings": "Settings",
          "Saved News": "Saved News",
          "Languages": "Languages",
          "Contact Us": "Contact Us",
          "News Fonts Size": "News Fonts Size",
          "Privacy Policy": "Privacy Policy",
          "About Us": "About Us",
          "Light Mode": "Light Mode",
          "Dark Mode": "Dark Mode",
          "Logout": "Logout",
          "Appearance": "Appearance",
          "Title Size": "Title Size",
          "Descriptions Size": "Descriptions Size",
          "Content Size": "Content Size",
          "Demo": "Demo",
          "News Title Dummy : ": "News Title Dummy : ",
          "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form ":
              "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form ",
          "Cate Name": "Cate Name",
          "City Name": "City Name",
          "By AuthorName": "By AuthorName",
          "Like": "Like",
          "Comments": "Comments",
          "Save": "Save",
          "Share": "Share",
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.":
              "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
          "Write a message...": "Write a message...",
          "Full Name": "Full Name",
          "Email Address": "Email Address",
          "Message": "Message",
          "Submit": "Submit",
          "By ": "By ",
          "Listen News": "Listen News",
          "See Another News..": "See Another News..",
          "No Data Found": "No Data Found",
          "Save Todo and Retrun to List": "Save Todo and Retrun to List",
          "Get Latest News": "Get Latest News",
          "Fast and accurate updates on the InitNews News App will ensure that you find the latest news headlines on your finger tips in different 9 languages. The app is built especially for android and iOS devices.":
              "Fast and accurate updates on the InitNews News App will ensure that you find the latest news headlines on your finger tips in different 9 languages. The app is built especially for android and iOS devices.",
          "Trusted Publishers": "Trusted Publishers",
          "Get world news, entertainment news, TV & cinema gossips, cricket updates, horoscope, weather, employment news, defense, stock updates & much more":
              "Get world news, entertainment news, TV & cinema gossips, cricket updates, horoscope, weather, employment news, defense, stock updates & much more",
          "Breaking News": "Breaking News",
          "Informative stories and features to improve your Lifestyle – Health, Wellness, Fitness, Food and Recipes, Travel and much more.":
              "Informative stories and features to improve your Lifestyle – Health, Wellness, Fitness, Food and Recipes, Travel and much more.",
          "Instant Notifications": "Instant Notifications",
          "Get Latest News Notifications, Get customized content through a recommended stream of news, videos & photos":
              "Get Latest News Notifications, Get customized content through a recommended stream of news, videos & photos",
          "Skip": "Skip",
          "Previous": "Previous",
          "Get Started": "Get Started",
          "Next": "Next",
          "Password": "Password",
          "Forgot Password ?": "Forgot Password ?",
          "Sign In": "Sign In",
          "Don't have account ?": "Don't have account ?",
          "Sign Up": "Sign Up",
          "First Name": "First Name",
          "Last Name": "Last Name",
          "Mobile Number": "Mobile Number",
          "You have already account ?": "You have already account ?",
          "Log in": "Log in",
          "Forgot Password": "Forgot Password",
          "Please enter Email so we can help to recover your password.":
              "Please enter Email so we can help to recover your password.",
          "Send OTP": "Send OTP",
          "Verification": "Verification",
          "Enter the OTP code from the email we just send you.":
              "Enter the OTP code from the email we just send you.",
          "Continue": "Continue",
          "Reset Password": "Reset Password",
          "Enter your new password and confirm it.":
              "Enter your new password and confirm it.",
          "Confirm Password": "Confirm Password",
          "Search": "Search",
          "Developed By ": "Developed By ",
          "Read": "Read",
          "size must be less than or equal to 8":
              "size must be less than or equal to 8",
          "Please add comments": "Please add comments",
          "All fields are required": "All fields are required",
          "Email is not valid": "Email is not valid",
          "New Mail Request Received": "New Mail Request Received",
          "You have received new mail": "You have received new mail",
          "New Contact Details": "New Contact Details",
          "We have received your request, we will respond on your issue soon":
              "We have received your request, we will respond on your issue soon",
          "Contact Information Sent": "Contact Information Sent",
          "Email address is required": "Email address is required",
          "Password is required": "Password is required",
          "Something went wrong while signup":
              "Something went wrong while signup",
          "Something went wrong": "Something went wrong",
          "password does not match": "password does not match",
          "Home": "Home",
          "Videos": "Videos"
        },
        "hi_IN": {
          "Profile": "प्रोफ़ाइल",
          "Sign In / Sign Up": "प्रवेश या साइन अप",
          "Settings": "समायोजन",
          "Saved News": "सहेजे गए समाचार",
          "Languages": "बोली",
          "Contact Us": "संपर्क करें",
          "News Fonts Size": "समाचार फोंट आकार",
          "Privacy Policy": "गोपनीयता नीति",
          "About Us": "हमारे बारे में",
          "Light Mode": "प्रकाश विधा",
          "Dark Mode": "डार्क मोड",
          "Logout": "लॉग आउट",
          "Appearance": "उपस्थिति",
          "Title Size": "शीर्षक आकार",
          "Descriptions Size": "विवरण आकार",
          "Content Size": "सामग्री आकार",
          "Demo": "डेमो",
          "News Title Dummy : ": "समाचार शीर्षक डमी:",
          "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form ":
              "प्रकाशन और ग्राफिक डिजाइन में, लोरम इप्सम एक प्लेसहोल्डर पाठ है जिसका उपयोग आमतौर पर दृश्य रूप को प्रदर्शित करने के लिए किया जाता है",
          "Cate Name": "केट नाम",
          "City Name": "शहर का नाम",
          "By AuthorName": "अधिवृषण द्वारा",
          "Like": "पसंद करना",
          "Comments": "टिप्पणियाँ",
          "Save": "सहेजें",
          "Share": "शेयर करना",
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.":
              "लोरम इप्सम केवल प्रिंटिंग और टाइपसेटिंग उद्योग का डमी टेक्स्ट है। लोरम इप्सम 1500 के दशक के बाद से उद्योग का मानक डमी पाठ रहा है, जब एक अज्ञात प्रिंटर ने टाइप की एक गैली ली और एक प्रकार का नमूना पुस्तक बनाने के लिए इसे हाथापाई की। यह न केवल पांच शताब्दियों से बच गया है, बल्कि इलेक्ट्रॉनिक टाइपिंग में छलांग भी है, जो अनिवार्य रूप से अपरिवर्तित शेष है। यह 1960 के दशक में लेट्रासेट शीट्स की रिलीज़ के साथ लोकप्रिय था जिसमें लोरेम इप्सम मार्ग थे, और हाल ही में एल्डस पेजमेकर जैसे डेस्कटॉप पब्लिशिंग सॉफ्टवेयर के साथ लॉरेम इप्सम के संस्करणों सहित।",
          "Write a message...": "एक सन्देश लिखिए...",
          "Full Name": "पूरा नाम",
          "Email Address": "ईमेल पता",
          "Message": "संदेश",
          "Submit": "प्रस्तुत",
          "By ": "द्वारा",
          "Listen News": "समाचार सुनो",
          "See Another News..": "एक और खबर देखें ।।",
          "No Data Found": "कोई डेटा नहीं मिला",
          "Save Todo and Retrun to List":
              "टोडो और रेट्रन को सूचीबद्ध करने के लिए सहेजें",
          "Get Latest News": "नवीनतम समाचार प्राप्त करें",
          "Fast and accurate updates on the InitNews News App will ensure that you find the latest news headlines on your finger tips in different 9 languages. The app is built especially for android and iOS devices.":
              "InitNews समाचार ऐप पर फास्ट और सटीक अपडेट यह सुनिश्चित करेगा कि आप विभिन्न 9 भाषाओं में अपनी उंगली युक्तियों पर नवीनतम समाचार सुर्खियों में पाते हैं। ऐप विशेष रूप से एंड्रॉइड और आईओएस उपकरणों के लिए बनाया गया है।",
          "Trusted Publishers": "विश्वसनीय प्रकाशक",
          "Get world news, entertainment news, TV & cinema gossips, cricket updates, horoscope, weather, employment news, defense, stock updates & much more":
              "विश्व समाचार, मनोरंजन समाचार, टीवी और सिनेमा गॉसिप्स, क्रिकेट अपडेट, कुंडली, मौसम, रोजगार समाचार, रक्षा, स्टॉक अपडेट और बहुत कुछ प्राप्त करें",
          "Breaking News": "आज की ताजा खबर",
          "Informative stories and features to improve your Lifestyle – Health, Wellness, Fitness, Food and Recipes, Travel and much more.":
              "अपनी जीवनशैली को बेहतर बनाने के लिए सूचनात्मक कहानियां और विशेषताएं - स्वास्थ्य, कल्याण, फिटनेस, भोजन और व्यंजनों, यात्रा और बहुत कुछ।",
          "Instant Notifications": "तत्काल सूचनाएं",
          "Get Latest News Notifications, Get customized content through a recommended stream of news, videos & photos":
              "नवीनतम समाचार सूचनाएं प्राप्त करें, समाचार, वीडियो और फ़ोटो की अनुशंसित स्ट्रीम के माध्यम से अनुकूलित सामग्री प्राप्त करें",
          "Skip": "छोडना",
          "Previous": "पहले का",
          "Get Started": "शुरू हो जाओ",
          "Next": "अगला",
          "Password": "कुंजिका",
          "Forgot Password ?": "पासवर्ड भूल गए ?",
          "Sign In": "साइन इन करें",
          "Don't have account ?": "खाता नहीं है?",
          "Sign Up": "साइन अप करें",
          "First Name": "पहला नाम",
          "Last Name": "उपनाम",
          "Mobile Number": "मोबाइल नंबर",
          "You have already account ?": "आप पहले से ही खाते हैं?",
          "Log in": "लॉग इन करें",
          "Forgot Password": "पासवर्ड भूल गए",
          "Please enter Email so we can help to recover your password.":
              "कृपया ईमेल दर्ज करें ताकि हम आपका पासवर्ड पुनर्प्राप्त करने में मदद कर सकें।",
          "Send OTP": "OTP भेजें",
          "Verification": "सत्यापन",
          "Enter the OTP code from the email we just send you.":
              "उस ईमेल से ओटीपी कोड दर्ज करें जिसे हम आपको भेजते हैं।",
          "Continue": "जारी रखना",
          "Reset Password": "पासवर्ड रीसेट",
          "Enter your new password and confirm it.":
              "अपना नया पासवर्ड दर्ज करें और इसकी पुष्टि करें।",
          "Confirm Password": "पासवर्ड की पुष्टि कीजिये",
          "Search": "खोज",
          "Developed By ": "द्वारा विकसित",
          "Read": "पढ़ना",
          "size must be less than or equal to 8":
              "आकार 8 से कम या बराबर होना चाहिए",
          "Please add comments": "कृपया टिप्पणियाँ जोड़ें",
          "All fields are required": "सभी फ़ील्ड आवश्यक हैं",
          "Email is not valid": "विद्युतडाक मान्य नहीं है",
          "New Mail Request Received": "नया मेल अनुरोध प्राप्त हुआ",
          "You have received new mail": "आपको नया मेल मिला है",
          "New Contact Details": "नया संपर्क विवरण",
          "We have received your request, we will respond on your issue soon":
              "हमें आपका अनुरोध मिला है, हम आपके मुद्दे पर जल्द ही जवाब देंगे",
          "Contact Information Sent": "संपर्क जानकारी भेजी",
          "Email address is required": "ईमेल पते की ज़रुरत है",
          "Password is required": "पासवर्ड की आवश्यकता है",
          "Something went wrong while signup": "साइनअप करते समय कुछ गलत हुआ",
          "Something went wrong": "कुछ गलत हो गया",
          "password does not match": "पासवर्ड मैच नहीं कर रहा है",
          "Home": "घर",
          "Videos": "वीडियो"
        },
        "es_DE": {
          "Profile": "Perfil",
          "Sign In / Sign Up": "Ingresar. Registrarse",
          "Settings": "Ajustes",
          "Saved News": "Noticias guardadas",
          "Languages": "Lengua",
          "Contact Us": "Contáctenos",
          "News Fonts Size": "Tamaño de las fuentes de noticias",
          "Privacy Policy": "Política de privacidad",
          "About Us": "Sobre nosotros",
          "Light Mode": "Modo de luz",
          "Dark Mode": "Modo oscuro",
          "Logout": "Cerrar sesión",
          "Appearance": "Apariencia",
          "Title Size": "Tamaño del título",
          "Descriptions Size": "Tamaño de descripciones",
          "Content Size": "Tamaño de contenido",
          "Demo": "Manifestación",
          "News Title Dummy : ": "Título de noticias Dummy:",
          "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form ":
              "En la publicación y el diseño gráfico, Lorem Ipsum es un texto de marcador de posición comúnmente utilizado para demostrar la forma visual",
          "Cate Name": "Nombre de Cate",
          "City Name": "Nombre de la ciudad",
          "By AuthorName": "Por fantasma",
          "Like": "Me gusta",
          "Comments": "Comentario",
          "Save": "Ahorrar",
          "Share": "Cuota",
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.":
              "Lorem Ipsum es simplemente un texto ficticio de la industria de impresión y tipografía. Lorem Ipsum ha sido el texto ficticio estándar de la industria desde el siglo XVI, cuando una impresora desconocida tomó una galera de tipo y lo revuelve para hacer un libro de muestras de tipo. Ha sobrevivido no solo cinco siglos, sino también el salto a la composición tipográfica electrónica, que se mantiene esencialmente sin cambios. Se popularizó en la década de 1960 con el lanzamiento de hojas de letraset que contienen pasajes Lorem Ipsum, y más recientemente con software de publicación de escritorio como Aldus Pagemaker, incluidas versiones de Lorem Ipsum.",
          "Write a message...": "Escribe un mensaje...",
          "Full Name": "Nombre completo",
          "Email Address": "Dirección de correo electrónico",
          "Message": "Mensaje",
          "Submit": "Enviar",
          "By ": "Por",
          "Listen News": "Escuchar noticias",
          "See Another News..": "Ver otra noticia ..",
          "No Data Found": "Datos no encontrados",
          "Save Todo and Retrun to List": "Guardar TODO y Returar a la lista",
          "Get Latest News": "Obtenga las últimas noticias",
          "Fast and accurate updates on the InitNews News App will ensure that you find the latest news headlines on your finger tips in different 9 languages. The app is built especially for android and iOS devices.":
              "Las actualizaciones rápidas y precisas en la aplicación InitNews News asegurarán que encuentre los últimos titulares de noticias en sus consejos de dedos en diferentes 9 idiomas. La aplicación está construida especialmente para dispositivos Android e iOS.",
          "Trusted Publishers": "Editores de confianza",
          "Get world news, entertainment news, TV & cinema gossips, cricket updates, horoscope, weather, employment news, defense, stock updates & much more":
              "Obtenga noticias mundiales, noticias de entretenimiento, chismes de televisión y cine, actualizaciones de cricket, horóscopo, clima, noticias de empleo, defensa, actualizaciones de acciones y mucho más",
          "Breaking News": "Noticias de última hora",
          "Informative stories and features to improve your Lifestyle – Health, Wellness, Fitness, Food and Recipes, Travel and much more.":
              "Historias y características informativas para mejorar su estilo de vida: salud, bienestar, estado físico, alimentos y recetas, viajes y mucho más.",
          "Instant Notifications": "Notificaciones instantáneas",
          "Get Latest News Notifications, Get customized content through a recommended stream of news, videos & photos":
              "Obtenga las últimas notificaciones de noticias, obtenga contenido personalizado a través de una transmisión recomendada de noticias, videos y fotos",
          "Skip": "Saltar",
          "Previous": "Anterior",
          "Get Started": "Empezar",
          "Next": "Próxima",
          "Password": "Clave",
          "Forgot Password ?": "Has olvidado tu contraseña ?",
          "Sign In": "Registrarse",
          "Don't have account ?": "¿No tienes cuenta?",
          "Sign Up": "Inscribirse",
          "First Name": "Primer nombre",
          "Last Name": "Apellido",
          "Mobile Number": "Número de teléfono móvil",
          "You have already account ?": "Ya tienes cuenta?",
          "Log in": "Iniciar sesión",
          "Forgot Password": "Has olvidado tu contraseña",
          "Please enter Email so we can help to recover your password.":
              "Ingrese el correo electrónico para que podamos ayudar a recuperar su contraseña.",
          "Send OTP": "Enviar OTP",
          "Verification": "Verificación",
          "Enter the OTP code from the email we just send you.":
              "Ingrese el código OTP desde el correo electrónico que le enviamos.",
          "Continue": "Continuar",
          "Reset Password": "Restablecer la contraseña",
          "Enter your new password and confirm it.":
              "Ingrese su nueva contraseña y confirme.",
          "Confirm Password": "Confirmar contraseña",
          "Search": "Búsqueda",
          "Developed By ": "Desarrollado por",
          "Read": "Leer",
          "size must be less than or equal to 8":
              "El tamaño debe ser menor o igual a 8",
          "Please add comments": "Por favor agregue comentarios",
          "All fields are required": "Todos los campos son obligatorios",
          "Email is not valid": "El correo no es válido",
          "New Mail Request Received": "Nueva solicitud de correo recibida",
          "You have received new mail": "Has recibido un nuevo correo",
          "New Contact Details": "Nuevos datos de contacto",
          "We have received your request, we will respond on your issue soon":
              "Hemos recibido su solicitud, pronto responderemos sobre su problema.",
          "Contact Information Sent": "Información de contacto enviada",
          "Email address is required": "Se requiere E-mail",
          "Password is required": "se requiere contraseña",
          "Something went wrong while signup":
              "Algo salió mal mientras se registra",
          "Something went wrong": "Algo salió mal",
          "password does not match": "las contraseñas no coinciden",
          "Home": "Casa",
          "Videos": "Videos"
        },
        "ar_AE": {
          "Profile": "الملف الشخصي",
          "Sign In / Sign Up": "تسجيل الدخول / التسجيل",
          "Settings": "إعدادات",
          "Saved News": "أنقذ الأخبار",
          "Languages": "اللغات",
          "Contact Us": "اتصل بنا",
          "News Fonts Size": "حجم خطوط الأخبار",
          "Privacy Policy": "سياسة الخصوصية",
          "About Us": "معلومات عنا",
          "Light Mode": "وضع الضوء",
          "Dark Mode": "الوضع المظلم",
          "Logout": "تسجيل خروج",
          "Appearance": "مظهر خارجي",
          "Title Size": "حجم العنوان",
          "Descriptions Size": "أوصاف حجم",
          "Content Size": "حجم المحتوى",
          "Demo": "العرض التوضيحي",
          "News Title Dummy : ": "العنوان الإخباري دمية:",
          "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form ":
              "في النشر والتصميم الجرافيكي ، Lorem ipsum هو نص نائب يستخدم عادة لإظهار النموذج المرئي",
          "Cate Name": "اسم كيت",
          "City Name": "اسم المدينة",
          "By AuthorName": "بواسطة Authorname",
          "Like": "مثل",
          "Comments": "تعليقات",
          "Save": "يحفظ",
          "Share": "يشارك",
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.":
              "Lorem ipsum هو ببساطة نص وهمية لصناعة الطباعة والأنشاش. لقد كان Lorem Ipsum نصًا وهميًا قياسيًا في الصناعة منذ القرن السادس عشر ، عندما أخذت طابعة غير معروفة من النوع ودافعت لإنشاء كتاب عينة من النوع. لقد نجا ليس فقط خمسة قرون ، ولكن أيضا قفزة في التنضيد الإلكتروني ، وتبقى دون تغيير بشكل أساسي. تم تعميمه في الستينيات من القرن الماضي مع إصدار أوراق Letraset التي تحتوي على مقاطع Lorem Ipsum ، ومؤخراً مع برنامج نشر سطح المكتب مثل Aldus Pagemaker بما في ذلك إصدارات Lorem Ipsum.",
          "Write a message...": "اكتب رسالة...",
          "Full Name": "الاسم الكامل",
          "Email Address": "عنوان البريد الالكترونى",
          "Message": "رسالة",
          "Submit": "يُقدِّم",
          "By ": "بواسطة",
          "Listen News": "استمع الأخبار",
          "See Another News..": "انظر أخبار أخرى ..",
          "No Data Found": "لاتوجد بيانات",
          "Save Todo and Retrun to List": "حفظ TODO واسترج",
          "Get Latest News": "احصل على أحدث الأخبار",
          "Fast and accurate updates on the InitNews News App will ensure that you find the latest news headlines on your finger tips in different 9 languages. The app is built especially for android and iOS devices.":
              "ستضمن التحديثات السريعة والدقيقة على تطبيق InitNews News أن تجد أحدث عناوين الأخبار على أطراف أصابعك بلغات مختلفة 9. تم تصميم التطبيق خاصة لأجهزة Android و iOS.",
          "Trusted Publishers": "الناشرين الموثوق بهم",
          "Get world news, entertainment news, TV & cinema gossips, cricket updates, horoscope, weather, employment news, defense, stock updates & much more":
              "احصل على الأخبار العالمية ، والأخبار الترفيهية ، وثرثرة التلفزيون والسينما ، وتحديثات الكريكيت ، وأبراج الأبراج ، والطقس ، وأخبار التوظيف ، والدفاع ، وتحديثات الأسهم وأكثر من ذلك بكثير",
          "Breaking News": "أخبار عاجلة",
          "Informative stories and features to improve your Lifestyle – Health, Wellness, Fitness, Food and Recipes, Travel and much more.":
              "قصص وميزات مفيدة لتحسين نمط حياتك - الصحة والعافية واللياقة والطعام والوصفات والسفر وأكثر من ذلك بكثير.",
          "Instant Notifications": "الإخطارات الفورية",
          "Get Latest News Notifications, Get customized content through a recommended stream of news, videos & photos":
              "احصل على أحدث إشعارات الأخبار ، واحصل على محتوى مخصص من خلال دفق موصى به من الأخبار ومقاطع الفيديو والصور",
          "Skip": "تخطى",
          "Previous": "سابق",
          "Get Started": "البدء",
          "Next": "التالي",
          "Password": "كلمة المرور",
          "Forgot Password ?": "هل نسيت كلمة السر ؟",
          "Sign In": "تسجيل الدخول",
          "Don't have account ?": "ليس لديك حساب؟",
          "Sign Up": "اشتراك",
          "First Name": "الاسم الأول",
          "Last Name": "اسم العائلة",
          "Mobile Number": "رقم الهاتف المحمول",
          "You have already account ?": "لديك حساب بالفعل؟",
          "Log in": "تسجيل الدخول",
          "Forgot Password": "هل نسيت كلمة السر",
          "Please enter Email so we can help to recover your password.":
              "الرجاء إدخال البريد الإلكتروني حتى نتمكن من المساعدة في استرداد كلمة المرور الخاصة بك.",
          "Send OTP": "إرسال OTP",
          "Verification": "تَحَقّق",
          "Enter the OTP code from the email we just send you.":
              "أدخل رمز OTP من البريد الإلكتروني الذي نرسله لك فقط.",
          "Continue": "يكمل",
          "Reset Password": "إعادة تعيين كلمة المرور",
          "Enter your new password and confirm it.":
              "أدخل كلمة المرور الجديدة وتأكيدها.",
          "Confirm Password": "تأكيد كلمة المرور",
          "Search": "بحث",
          "Developed By ": "طورت بواسطة",
          "Read": "اقرأ",
          "size must be less than or equal to 8":
              "يجب أن يكون الحجم أقل من أو يساوي 8",
          "Please add comments": "الرجاء إضافة تعليقات",
          "All fields are required": "جميع الحقول مطلوبة",
          "Email is not valid": "البريد الإلكتروني غير صالح",
          "New Mail Request Received": "تم استلام طلب البريد الجديد",
          "You have received new mail": "لقد تلقيت بريدًا جديدًا",
          "New Contact Details": "تفاصيل الاتصال الجديدة",
          "We have received your request, we will respond on your issue soon":
              "لقد تلقينا طلبك ، وسوف نرد على مشكلتك قريبًا",
          "Contact Information Sent": "معلومات الاتصال المرسلة",
          "Email address is required": "عنوان البريد الإلكتروني مطلوب",
          "Password is required": "كلمة المرور مطلوبة",
          "Something went wrong while signup": "حدث خطأ ما أثناء الاشتراك",
          "Something went wrong": "هناك خطأ ما",
          "password does not match": "كلمة السر غير متطابقة",
          "Home": "بيت",
          "Videos": "أشرطة فيديو"
        },
      };
}
